POST http://localhost:8080/user/login
Content-Type: application/json

{
    "id": "user",
    "password": "user"
}

###

GET http://localhost:8080/user/mypage
Authorization: eyJhbGciOiJI.OiJ1c2VyIiwiaWF0IjoxNzE1NjYzMjc1LCJleHAiOjE3MTU2NjY4NzV9.tYV6C3VLcI9_Dcx-ovm3JwjvybSQDua_0MxB-YVJDmo
Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ1c2VyIiwiaWF0IjoxNzE1NjYzMjc1LCJleHAiOjE3MTgyNTUyNzV9.unVkBk5NWAfDYgdn5KQF3cXcR65jTa1NG5PR-bikXY4

